# https://github.com/marketplace/actions/publish-docker

name: Publish to Docker
on:
#  push:
#    branches:
#      - "main"
#  schedule:
#    - cron: "10 6 * * *"
  workflow_dispatch:

jobs:

  build:
    name: "Build versions"
    runs-on: ubuntu-22.04

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - "5.36.0"
          - "5.34.1"
          - "5.32.1"
          - "5.30.3"
          - "5.28.3"
          - "5.26.3"
          - "5.24.4"
          - "5.22.4"
          - "5.20.3"
          - "5.18.4"
          - "5.16.3"
          - "5.14.4"

    steps:
      - uses: actions/checkout@v3
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: ${{ secrets.DOCKER_REPO }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_TOKEN }}
          dockerfile: Dockerfile
          buildargs: BASE=${{ matrix.perl-version }}
          tags: "${{ matrix.perl-version }}"
