# https://github.com/marketplace/actions/publish-docker

name: Publish to Docker
on:
#  push:
#    branches:
#      - "main"
#  schedule:
#    - cron: "10 6 * * *"
  workflow_dispatch:

jobs:

  latest-build:
    name: "Build latest"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: ${{ secrets.DOCKER_REPO }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_TOKEN }}
          dockerfile: Dockerfile
          #buildargs: BASE=bullseye
          tags: "latest"

  build:
    name: "Build versions"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - "5.36"
          - "5.34"
          - "5.32"
          - "5.30"
          - "5.28"
          - "5.26"
          - "5.24"
          - "5.22"
          - "5.20"
          - "5.18"
          - "5.16"
          - "5.14"

    steps:
      - uses: actions/checkout@v3
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: ${{ secrets.DOCKER_REPO }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_TOKEN }}
          dockerfile: Dockerfile
          buildargs: BASE=${{ matrix.perl-version }}
          tags: "${{ matrix.perl-version }}"
