# https://github.com/marketplace/actions/publish-docker

name: Publish Windows to Docker
on:
#  push:
#    branches:
#      - "main"
#  schedule:
#    - cron: "10 6 * * *"
  workflow_dispatch:

jobs:

  build:
    name: "Build versions"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - "5.32.1.1"

    steps:
      - uses: actions/checkout@v3
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: ${{ secrets.DOCKER_REPO }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_GITHUB_TOKEN }}
          dockerfile: Dockerfile-windows
          buildargs: PERL_VERSION=${{ matrix.perl-version }}
          tags: "win-${{ matrix.perl-version }}"
